### ISSUE TITLE
反馈问题：起点书源失效

### ISSUE THREAD

**Issue by 0987363** [XIU2/Yuedu#100]
### 阅读版本

3.23.073011

### 书源名称

起点

### 问题描述

失效，搜索不到

### 附加截图

![微信图片_20240504131941](https://github.com/XIU2/Yuedu/assets/7909837/6e6bb7c5-bd7c-4562-8728-3a310de89fd8)

**Comment by XIU2** [comment]
没有失效，搜不到是起点自身的问题，个别书通过起点网页接口是搜不到的。
