### ISSUE TITLE
书源请求：秀婷看书

### ISSUE THREAD

**Issue by jason93110** [XIU2/Yuedu#104]
### 网站地址

https://www.xiuting.cc/

### 推荐原因

因为起点防盗功能，现在很多小说都不能第一时间更新，得晚几天才能显示全部内容，这个小说网站比所有的小说网站更新快好几天，因为刚更新的时候这个网站小说内容使用的是图片格式，等其他盗版网站更新后这个才会跟着转换成文字

**Comment by jason93110** [comment]
例如《逼我重生是吧》这本小说，所有小说网内容更新都没这个快，其它小说网只能获取开头，这个能获取全部内容

**Comment by XIU2** [comment]
但问题是，阅读书源要么设置为图片书源，要么设置为文字书源，是无法混用的。。。

**Comment by jason93110** [comment]
图片书源就行，因为最新章节都是用的图片格式，文字格式的章节其它书源也齐全

**Comment by XIU2** [comment]
但问题是我没写过图片书源。。。

因为这些书源都是我自用的，所以一直以来写的都是文字书源。
