### ISSUE TITLE
反馈问题：69书吧 书源失效

### ISSUE THREAD

**Issue by esme518** [XIU2/Yuedu#106]
### 阅读版本

3.24.092019

### 书源名称

69书吧

### 问题描述

网站添加了Cloudflare人机验证导致书源失效

**Comment by XIU2** [comment]
这网站竟然从 CloudFront 迁移到了 Cloudflare CDN（或者说套了 CDN）。

那这样的话，对书源就很不友好了，虽然这种人机验证是可以解决的，但需要手动过验证，这意味着每次搜索、更新书籍目录、阅读新章节、换书源时都需要手动过一次验证（不清楚这网站设置的验证有效期是多长时间，一般都是十分钟到半小时左右吧，就需要重新验证才能继续）。

**Comment by XIU2** [comment]
已更新解决：

- 新增 [阿酷小说]
- 修复 [69书吧]、[和图书]、[思路客]、[武林中文网]、[大文学无错小说网]
- 恢复 [顶点小说 ddxs]
- 更新 [铅笔小说]
- 优化 其他一些书源规则(如详情页分类更详细)
- 移除 失效书源...

其中 [阿酷小说]、[69书吧]、[和图书]、[思路客]、[武林中文网]、[大文学无错小说网]、[顶点小说 ddxs] 都是有全站人机验证或者搜索人机验证的。
从早上忙活到现在，把他们全都给处理了，其中 `[顶点小说 ddxs]` 是以前因为人机验证而删除的，我又给翻出来恢复加上了。

我都分组+注释了：

对于` 人机验证-全站 ` 的书源：
> 注意：该书源【全站】启用了 "人机验证"，因此使用过程中（搜索、换书源、更新目录、加载新章节等）可能会出现人机验证界面，通过后一段时间内不会再验证，如果不喜欢可以禁用该书源。

对于` 人机验证-搜索 ` 的书源：
> 注意：该书源【搜索】启用了 "人机验证"，因此使用过程中（搜索、换书源）可能会出现人机验证界面，通过后一段时间内不会再验证，如果不喜欢可以禁用该书源。

**Comment by XIU2** [comment]
69书吧 昨天晚上又有所变动，我这边也更新书源了，你记得更新。

- 优化 [69书吧] 人机验证相关代码（因为网站改为只保留了详情页和目录页的人机验证，所以移除了搜索页、分类页、正文页的相关代码）
- 修复 [69书吧]、[69好书] 详情页最新章节显示问题（网站自身改为了显示最新章节的地址而不是章节名导致的）
