### ISSUE TITLE
那个UAA友爱爱 为什么那么多大神都无法修复？

### ISSUE THREAD

**Issue by SuperBlackWednesday** [XIU2/Yuedu#108]
### 网站地址

https://m.uaa004.com/

### 推荐原因

这个网站对阅读3.0屏蔽了吗？

**Comment by XIU2** [comment]
申请必读第一条：不接受 `轻小说、R18 小说、小说下载站、漫画` 等类型的网站申请（因为我不看这些类型）

****

另外，对于这个网站，前几天我吃瓜了，好像是因为贴吧里有个人拿着大家编写的书源倒卖（一个人 100 ？），然后书源失效了还喷别人什么的，具体我也没仔细了解，然后各个书源编写大神都被骂被恶心到了，于是就停止发布修复版的书源了。
