### ISSUE TITLE
有声听书网

### ISSUE THREAD

**Issue by SuperBlackWednesday** [XIU2/Yuedu#109]
### 网站地址

m.ysts.cc

### 推荐原因

源仓库的不好使了  本来可以用阅读3.0的朗读功能   但是最近听一个恐怖类的小说  那朗读功能没感觉啊  还是真人制作的有感觉
那个www.ysts.cc不知道为什么干脆进不去  只有这个m开头的能在手机上听  但是网页的很卡啊  大神帮个忙吧  编程那些符号我看着就像乱码一样 完全搞不懂

**Comment by XIU2** [comment]
额，我不做听书源的（也从没做过）。。。稍后会补充进申请必读的。
