### ISSUE TITLE
github.io DNS污染

### ISSUE THREAD

**Issue by withsalt** [XIU2/yuedu#11]
我没法测试我是我的网络问题还是怎么回事，使用移动4G，默认DNS，github.io被解析为127.0.0.1。电信访问正常，但是下载速度巨慢，获取书源时大概率timeout。
如果可以的话，建议搞个gitee镜像。

**Comment by XIU2** [comment]
这个问题前几天有人说过，我查了下，应该是广东本地 DNS 的问题，不属于 DNS 污染。
全国基本上只有广东才会解析为 127.0.0.1（或 ipv6 的 ::1）。
你尝试更换 DNS 后重试。
![1](https://user-images.githubusercontent.com/54703944/91268509-0d301b80-e7a8-11ea-8ba5-78b22e8ed195.png)

**Comment by XIU2** [comment]
如果发展到其他地区也变成这样的话，到时候我把本项目的默认域名改成我自己的域名就行了。

**Comment by withsalt** [comment]
感谢测试，不过我在成都【狗头】，难受~

**Comment by XIU2** [comment]
至于访问速度慢，我看了下，github.io 解析的IP看延迟应该是亚洲的，联通和移动延迟都很低，最快的是 广东移动 11.2ms（虽然广东本地 DNS 解析错误） 。
至于电信似乎最快的也是河南 152.6ms，平均延迟 258.8ms ...
四川移动延迟也很低，但是你 DNS 解析错误 ...

**Comment by XIU2** [comment]
我折腾了下，更换了域名和服务器，你可以试试速度怎么样。
https://yuedu.xiu2.xyz/shuyuan

**Comment by withsalt** [comment]
非常感谢，速度很快。以后一直用这个地址了吗？

**Comment by XIU2** [comment]
域名是不会变了，服务器的话如果不出意外（比如突然网络质量严重下降）的话，也不会变。
而且我前几天还一起把我其他几个项目的 GitHub Pages 也都换成这个服务器了。

这个服务器和 Github 自己的服务器可以说有点相反。
Github 的服务器是 移动友好，联通居中、电信扑街，
而这个服务器则是 电信友好、联通居中、移动相对它们差点（但还是不错），全国测速一片绿。

**Comment by XIU2** [comment]
我特么爆炸了，这才用了不到三天，新服务器就爆炸了，这 Vercel 也太坑了，把我账号都给封了，也没有通知，也没有说原因，也是别人跟我说我的网站挂了我才发现的。。。印象分瞬间从 +666 变成 -999！

我先把服务器改回 Github 的服务器，不过域名就不改回去了，以后都是这个域名了。
我已经发邮件询问了，等等看 Vercel 怎么说。
