### ISSUE TITLE
书源请求：番茄免费小说

### ISSUE THREAD

**Issue by fcmxmk** [XIU2/Yuedu#111]
### 网站地址

https://fanqienovel.com/page/.*[0-9]{19}.*

### 推荐原因

> 书源来自论坛国庆节福利：https://www.yckceo.com/yuedu/shuyuans/content/id/638.html

[源仓库](https://www.yckceo.com/yuedu/shuyuan)、[Yiove 综合书源库](https://shuyuan.yiove.com/complex) 书源已测试过，无可用番茄免费小说书源。书源 http://81.70.63.5:369/（//二改于浅殇的Pyfqweb接口书源）已经过期，我有自己的服务器，想问下大佬要如何配置类似 81.70.63.5:369 的番茄api接口？

**Comment by XIU2** [comment]
番茄书源制作难度太高（主要是经过这么多年的修修补补，剩下的官方接口“漏洞”基本上都见光死了），我是不会考虑制作的。

至于自建番茄 API 接口，这我也不知道，我没搞过。。。
