### ISSUE TITLE
怎么捐赠？

### ISSUE THREAD

**Issue by jiasu001xyz** [XIU2/Yuedu#12]
用了很久了，很感谢，但没找到捐赠渠道，希望能贴一个收款码，让我们想捐赠的，有个地方。可能不多，但是心意。

**Comment by XIU2** [comment]
你有知乎账号吗？有的话可以去知乎文章赞赏：https://zhuanlan.zhihu.com/p/83583790  
这两年打赏赞赏人数也没几个人。。。

**Comment by XIU2** [comment]
收到了~  
> 没有其他问题的话，就关闭该 Issues 吧。

**Comment by jiasu001xyz** [comment]
知乎链接赞赏捐赠。https://zhuanlan.zhihu.com/p/83583790
