### ISSUE TITLE
推荐小说网站

### ISSUE THREAD

**Issue by im-FL** [XIU2/Yuedu#14]
哨兵小说网：
https://m.xdhtxt.com/

**Comment by jjss520** [comment]
有josn吗？

**Comment by im-FL** [comment]
> 有josn吗？

没有啊，想让大佬 @XIU2 试试写书源。

**Comment by XIU2** [comment]
看了下，感觉这个小说网也不怎么样。。。

首页推荐的那几个热门小说，我看好多最后更新时间是**上星期的（4 月 24 日）**。
我尝试搜索小说并对搜索链接抓包发现该网站似乎是**从别的小说网站抓取资源**的（比如搜索 大奉打更人 时在返回数据中看到了 `bookFileUrl: "http://www.biquge.info/62_62245/"`），我尝试访问发现这个笔趣阁的网站已经更新到今天了（相差 10 章），有点迷。。。

**Comment by im-FL** [comment]
> 看了下，感觉这个小说网也不怎么样。。。
> 
> 首页推荐的那几个热门小说，我看好多最后更新时间是**上星期的（4 月 24 日）**。
> 我尝试搜索小说并对搜索链接抓包发现该网站似乎是**从别的小说网站抓取资源**的（比如搜索 大奉打更人 时在返回数据中看到了 `bookFileUrl: "http://www.biquge.info/62_62245/"`），我尝试访问发现这个笔趣阁的网站已经更新到今天了（相差 10 章），有点迷。。。

ok！抱歉给您带来麻烦了！
