### ISSUE TITLE
起点中文书源的内容怎么不全呢？是我哪里设置不正确吗？

### ISSUE THREAD

**Issue by China-Huanghe** [XIU2/Yuedu#17]
加载之后**只有前两页的内容**，就像是**没有付费**，只能看到前面一点**免费内容**一样

**Comment by XIU2** [comment]
起点中文书源只能看免费内容，付费的当然看不到啦。

**Comment by China-Huanghe** [comment]
> 起点中文书源只能看免费内容，发现的当然看不到啦。怎么可能会破解该内容。。。
> 
> 我一般是用起点中文书源看前面的免费章节，按章节就切换到其他的书源。

好的
