### ISSUE TITLE
书源请求：英文小说网站与app

### ISSUE THREAD

**Issue by prenfic** [XIU2/Yuedu#20]
#APP
1. Goodnovel
LINK: https://play.google.com/store/apps/details?id=com.read.goodnovel
2. Webnovel
LINK: https://play.google.com/store/apps/details?id=com.qidian.Int.reader

#网站
1. Wuxiaworld（这个官方app有点丑啊 而且我用eink那动画关不掉用着很难受 ps: 源仓库的已经用不了了）
LINK: https://www.wuxiaworld.com/
2. Wuxiaworldsite（目测是盗版的wuxiaworld 而且源仓库的也用不了了）
LINK: https://wuxiaworldsite.com/page/2/
3. Allnovel （言情小说居多）
LINK: https://allnovel.net/
4. Readnobelfull （主打全本小说翻译跟轻小说）
LINK: https://readnovelfull.com/

ps:
希望可以的话琢磨一下login功能😶 有些氪金了 那coins没用完🤣

**Comment by prenfic** [comment]
那 中文的我目前是用这几个
https://shuyuan.miaogongzi.cc/shuyuan/931067fe5ab34286b5803d7a43092c11.json

你可以尝试一下？

其中笔趣阁跟神书宝用得比较多

**Comment by prenfic** [comment]
我发那些app跟网站是希望能帮忙弄成源🤣
要不eink太多app 那动画又不能关 用得很难受 希望能都整合到legado

**Comment by XIU2** [comment]
emmm，不感兴趣的话我就没有动力去制作书源，毕竟制作一个简单的书源也需要最少一二十分钟。。。

**Comment by prenfic** [comment]
怪不得 没关系 不强求啊

最近同一本小说换成了英文看 一来看一下别人咋做的翻译 二来算是增进外语

ps:
中文部分供参考啊 至少目前用得挺全乎的

**Comment by XIU2** [comment]
这个项目里的书源就是我自用的，顺便分享出来，如果有人有好的小说网站，我会将其制作为书源并顺便自用~

**Comment by prenfic** [comment]
我这里边就上传了几个各路大佬帮忙从各种我觉得好用的app弄出来的（加上有些是酷安下的），都是我觉得挺全乎的源（有些含发现）

**Comment by XIU2** [comment]
哈哈，我先导入用一段时间看看质量如何，如果不错的话就加入项目中~
