### ISSUE TITLE
书源请求：书趣阁

### ISSUE THREAD

**Issue by xiaozixun** [XIU2/Yuedu#21]
https://www.shuquge.com/

**Comment by xiaozixun** [comment]
> 
> 
> 正看着看着，突然网站就挂了好像。。。 宽带和手机 4G 都无法访问了。

这就不知道了，不过我使用了几次倒是没问题
还有个：m.aixdzs.com，或许也可以

**Comment by XIU2** [comment]
书源写完了：
```
{
    "bookSourceUrl": "https://www.shuquge.com",
    "bookSourceType": "0",
    "bookSourceName": "书趣阁",
    "bookSourceGroup": "",
    "bookSourceComment": "",
    "loginUrl": "",
    "bookUrlPattern": "",
    "header": "",
    "searchUrl": "/search.php,{\n\"method\":\"POST\",\n\"body\":\"s=0000000000000000000&searchkey={{key}}\"\n}",
    "exploreUrl": "",
    "enabled": true,
    "enabledExplore": false,
    "weight": 0,
    "customOrder": 0,
    "lastUpdateTime": 1633660598388,
    "ruleSearch": {
        "bookList": "class.bookbox",
        "name": "class.bookname.0@tag.a.0@text",
        "author": "class.author.0@text",
        "kind": "class.cat.0@text##分类：",
        "lastChapter": "class.update.0@tag.a.0@text",
        "bookUrl": "class.bookname.0@tag.a.0@href"
    },
    "ruleExplore": {},
    "ruleBookInfo": {
        "name": "class.info.0@tag.h2.0@text",
        "author": "class.small.0@tag.span.0@text##作者：",
        "kind": "class.small.0@tag.span.1@text##分类：",
        "wordCount": "class.small.0@tag.span.3@text##字数：",
        "lastChapter": "class.small.0@tag.span.5@tag.a.0@text",
        "intro": "class.intro.0@textNodes##简介：",
        "coverUrl": "class.cover.0@tag.img.0@src"
    },
    "ruleToc": {
        "chapterList": "//dt[2]/following-sibling::dd",
        "chapterName": "tag.a.0@text",
        "chapterUrl": "tag.a.0@href"
    },
    "ruleContent": {
        "content": "id.content.0@textNodes##(https:\\/\\/.+)|(请记住本书.+)"
    }
}
```

**Comment by xiaozixun** [comment]
> 
> 
> 书源写完了，稍后会更新加到本项目列表中：
> 
> ```
> {
>     "bookSourceUrl": "https://www.shuquge.com",
>     "bookSourceType": "0",
>     "bookSourceName": "书趣阁",
>     "bookSourceGroup": "",
>     "bookSourceComment": "",
>     "loginUrl": "",
>     "bookUrlPattern": "",
>     "header": "",
>     "searchUrl": "/search.php,{\n\"method\":\"POST\",\n\"body\":\"s=0000000000000000000&searchkey={{key}}\"\n}",
>     "exploreUrl": "",
>     "enabled": true,
>     "enabledExplore": false,
>     "weight": 0,
>     "customOrder": 0,
>     "lastUpdateTime": 1633660598388,
>     "ruleSearch": {
>         "bookList": "class.bookbox",
>         "name": "class.bookname.0@tag.a.0@text",
>         "author": "class.author.0@text",
>         "kind": "class.cat.0@text##分类：",
>         "lastChapter": "class.update.0@tag.a.0@text",
>         "bookUrl": "class.bookname.0@tag.a.0@href"
>     },
>     "ruleExplore": {},
>     "ruleBookInfo": {
>         "name": "class.info.0@tag.h2.0@text",
>         "author": "class.small.0@tag.span.0@text##作者：",
>         "kind": "class.small.0@tag.span.1@text##分类：",
>         "wordCount": "class.small.0@tag.span.3@text##字数：",
>         "lastChapter": "class.small.0@tag.span.5@tag.a.0@text",
>         "intro": "class.intro.0@textNodes##简介：",
>         "coverUrl": "class.cover.0@tag.img.0@src"
>     },
>     "ruleToc": {
>         "chapterList": "//dt[2]/following-sibling::dd",
>         "chapterName": "tag.a.0@text",
>         "chapterUrl": "tag.a.0@href"
>     },
>     "ruleContent": {
>         "content": "id.content.0@textNodes##(https:\\/\\/.+)|(请记住本书.+)"
>     }
> }
> ```
> 
> 另外，你给的另一个网站 m.aixdzs.com 是繁体呀。。。

抱歉，我之前有事，一直没顾上开电脑。所以现在才回复。
辛苦了，不过它的确是简体，不过有时候会变繁体，不知道是不是网络原因；还有这个网站有时会访问不了。
![批注 2021-10-09 124511](https://user-images.githubusercontent.com/22409452/136644384-2ae0ab47-b28f-4254-a6f0-5f1edc5d846f.png)

**Comment by XIU2** [comment]
那就先这样吧~
