### ISSUE TITLE
书源请求：http://www.banzhu123.com/33/33566/

### ISSUE THREAD

**Issue by tutu2147** [XIU2/Yuedu#22]
拜托希望制作http://www.banzhu123.com/33/33566/小说网站的书源~如果这不合适，换个类型吧。

**Comment by ayden19** [comment]
兄弟，差点出不来

**Comment by XIU2** [comment]
噫，奇怪，才看到这个 Issues。。。
不过我对这类小说不感兴趣，所以没什么动力制作为书源的。。。

**Comment by tutu2147** [comment]
嗯，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月29日(周六) 上午9:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XIU2/Yuedu] 书源请求：http://www.banzhu123.com/33/33566/ (Issue #22)




 
噫，奇怪，才看到这个 Issues。。。
 不过我对这类小说不感兴趣，所以没什么动力制作为书源的。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
