### ISSUE TITLE
反馈问题：安卓阅读备份导入ios源阅读失败

### ISSUE THREAD

**Issue by Yiweiwangau** [XIU2/Yuedu#23]
您好，我试了一下把安卓端的zip备份文件导入到ios源阅读，出现导入失败的情况。备份文件里有书源和之前放在书架上的书.我试过直接改名覆盖和把zip里同名文件覆盖，都不行
请问一下目前安卓导入ios段的正确方法应该是什么样的？谢谢

**Comment by XIU2** [comment]
不知道呀，我没有 IOS 设备，没有用过，只看到 IOS 阅读的作者说和 Android 阅读的规则一致（不是一个作者）。

**Comment by Yiweiwangau** [comment]
不好意思我看错了，看成了您的github是阅读app的页面
