### ISSUE TITLE
反馈问题：XX 书源失效巴拉巴拉（记得修改该示例标题）

### ISSUE THREAD

**Issue by DeanShiDirect** [XIU2/Yuedu#25]
书源分享地址： https://yuedu.xiu2.xyz
网络导入地址： https://yuedu.xiu2.xyz/shuyuan
本地导入地址： 去上面的书源分享地址里点击 [下载文件]
历史书源文件： https://yuedu.xiu2.xyz/old

哥们 导入你的书源后  显示 书源格式错误。网址错 json文件错

**Comment by XIU2** [comment]
我这边导入正常，请确保你是阅读 3.X 版本。
