### ISSUE TITLE
反馈问题：章节名称导致排版乱了 有可能还会造成重复章节名称

### ISSUE THREAD

**Issue by Jadmin3** [XIU2/Yuedu#26]
版本是苹果市场最新版本
![f9d13e29ec25024b029541bcea21eee](https://user-images.githubusercontent.com/34308316/145916331-af3106cd-3e95-4b28-9134-8662982fcebf.jpg)
章节名称导致排版乱了 有可能还会造成重复章节名称

**Comment by Jadmin3** [comment]
强迫症好难受啊~~大佬~

**Comment by XIU2** [comment]
你问错地方了吧，我这里并不是《阅读》APP 的官方项目，只是分享书源罢了。。。
官方： https://github.com/gedoor/legado

**Comment by Jadmin3** [comment]
我以为是app。。。对不起。。
