### ISSUE TITLE
求订阅源and替换净化规则，要来来一套

### ISSUE THREAD

**Issue by China-Huanghe** [XIU2/Yuedu#27]
求订阅源and替换净化规则，要来来一套

**Comment by XIU2** [comment]
不推荐使用别人制作的 替换净化规则，误伤太严重。
我都是自己看书的时候，遇到一些小说源网站自己插入的广告文字之类的时，手动写规则。

**Comment by China-Huanghe** [comment]
那订阅源呢，来一套精简强大的吧

XIU2 ***@***.***> 于 2022年1月3日周一 上午8:57写道：

**Comment by XIU2** [comment]
这个项目不就是吗？我自用的书源，为了方便使用和分享，我才创建了这个项目。

**Comment by China-Huanghe** [comment]
订阅源跟书源不一样的

XIU2 ***@***.***> 于 2022年1月3日周一 上午10:42写道：

**Comment by XIU2** [comment]
那我就没有了~
我这个项目只是自用的书源罢了。

**Comment by China-Huanghe** [comment]
好的，那也很不错了

XIU2 ***@***.***> 于 2022年1月3日周一 上午11:03写道：
