### ISSUE TITLE
书源请求：博看小说网

### ISSUE THREAD

**Issue by rihalvnium76** [XIU2/Yuedu#28]
博看小说网  网址：https://www.kchao.net/

有一些新书其它网站都没有，而这个网站有

**Comment by XIU2** [comment]
看了下，搞不了，这网站的搜索请求是**加密**的（非常见加密方案），因此无法模拟。。。

阅读 APP 的书源，必须要有搜索规则，无论是搜书还是换书源都是 APP 去搜索一遍获取书籍地址，然后再去提取目录、正文。

不过随着阅读 APP 的名气越来越大，越来越多的小说网站都对搜索功能做了特殊处理，以避免用户不来网站看（靠广告盈利）。

**Comment by rihalvnium76** [comment]
> 看了下，搞不了，这网站的搜索请求是**加密**的（非常见加密方案），因此无法模拟。。。
> 
> 阅读 APP 的书源，必须要有搜索规则，无论是搜书还是换书源都是 APP 去搜索一遍获取书籍地址，然后再去提取目录、正文。 因此搜索规则是整个书源的**根基**，书源能不能做，主要取决于能不能写出搜索规则。
> 
> 不过随着阅读 APP 的名气越来越大，越来越多的小说网站都对搜索功能做了特殊处理，以避免用户不来网站看（靠广告盈利）。

外行人想问下不能模拟浏览器那样加载完网页后再把多余的网页内容去除整理吗？

**Comment by XIU2** [comment]
这种方法有（一些爬虫爬取动态加载内容的网站就是这样干的），但我不知道阅读 App 是否支持这么做。
