### ISSUE TITLE
功能建议：添加蓝光过滤

### ISSUE THREAD

**Issue by ayden19** [XIU2/Yuedu#30]
是否可以添加蓝光过滤功能，看起来会更舒服一点。虽然不知道蓝光过滤是否有用，但如果真有用，还是希望后续更新能添加一个蓝光过滤的功能，谢谢

**Comment by XIU2** [comment]
你找错人了，这并不是《阅读》APP 官方项目，这只是我分享自用书源的项目。。。
官方项目：https://github.com/gedoor/legado
