### ISSUE TITLE
书源请求：大文学无错小说网

### ISSUE THREAD

**Issue by ayden19** [XIU2/Yuedu#32]
小说网站 URL：https://www.wucuoxs.com/
推荐原因：更新快于此app中已有的书源，此外内容完整，如夜的命名术。

**Comment by XIU2** [comment]
这网站在每一个章节都塞进去了一个 咪咪阅读 广告。。。

**Comment by XIU2** [comment]
总之，我还是给加上了，你导入书源吧。
