### ISSUE TITLE
反馈问题：番茄小说发现文字乱码

### ISSUE THREAD

**Issue by rihalvnium76** [XIU2/Yuedu#33]
番茄小说发现文字乱码（如图所示），其它书源（部分）的搜索与发现文字正常
疑似书源编码问题

书源更新时间 20220320
阅读APP v3.22.031722

![image](https://user-images.githubusercontent.com/57667144/159197436-76d3cfbd-ed79-4752-8f68-6ad60681ac74.png)

**Comment by XIU2** [comment]
看了下，只有发现里有一些乱码，我尝试手动访问发现 URL，也是这样子的。
应该是书源网站本身改动了什么东西，不过这个书源并不是我写的，而是别人推荐给我的，当时 "发现" 还是正常的。。。
