### ISSUE TITLE
书源请求：斗破小说网站

### ISSUE THREAD

**Issue by klmahua** [XIU2/Yuedu#34]
网站地址：http://doupocangqiong1.com/
推荐原因：最近全网小说都无更新，只有这个站有新的更新内容，，笔趣阁一大堆网站好像都不行了

**Comment by XIU2** [comment]
你这个**全网小说都无更新**结论是哪来的。。。

**Comment by klmahua** [comment]
比如本月的销量冠军 《夜的命名术 》  都没最近的几章内容

**Comment by XIU2** [comment]
我搜了下我书架里还在连载的小说，这网站也多少存在这种情况。。。
![01](https://user-images.githubusercontent.com/54703944/165872009-1232a25f-8dd0-4637-9cb0-e59798f0a641.png)

**Comment by XIU2** [comment]
不过对我影响没那么大，这些年我都没找到几本合我口味的书了。。。
搞得我基本上都在吃老本，对以前收藏的小说翻来覆去看好几遍了。。。

**Comment by klmahua** [comment]
呵呵  推荐看  滚开大神的小说   你一定喜欢

**Comment by klmahua** [comment]
推荐的这个网站  权重很高   很多小说站都是互相采。。。一个不行  都废了

**Comment by XIU2** [comment]
书源写完了，你更新一下试试吧。
