### ISSUE TITLE
有的epub格式书籍无法正常阅读，在其他阅读app内可以正常使用，

### ISSUE THREAD

**Issue by justincnn** [XIU2/yuedu#4]
具体如连接的书籍，
https://www.lanzous.com/i9i4y5a

出现问题有两个：
1.图片无法显示，
2.除了前言外，正文内容无法显示，

目前使用的app版本为play store的最新版

**Comment by XIU2** [comment]
emmm 我这个项目只是整理 [阅读APP] 的书源，并不是 阅读APP 开发项目。
请去官方开发项目提问：https://github.com/gedoor/MyBookshelf
