### ISSUE TITLE
反馈问题：起点又获取不到目录了

### ISSUE THREAD

**Issue by xiaozixun** [XIU2/Yuedu#44]
版本:3.22.052723
名称:起点中文
情况:目录获取不到

好比https://github.com/XIU2/Yuedu/issues/31

不过，比较奇怪的是在退出阅读后，重新进入app就能获取到目录

**Comment by xiaozixun** [comment]
> 



> 我这边调试结果正常：
> 
> ```
> 源《起点中文》保存成功！使用搜索关键字“科技”开始调试...
> [00:00.000] ⇒开始搜索关键字:科技
> [00:00.002] ︾开始解析搜索页
> [00:00.436] ≡获取成功:/search?kw=科技
> [00:00.438] ┌获取书籍列表
> [00:00.695] └列表大小:10
> [00:00.714] ┌获取书名
> [00:00.720] └科技之锤
> [00:00.720] ┌获取作者
> [00:00.723] └一桶布丁
> [00:00.723] ┌获取分类
> [00:00.725] └连载,都市
> [00:00.725] ┌获取字数
> [00:00.727] └228.89万
> 12.28万
> [00:00.727] ┌获取最新章节
> [00:00.729] └完本感言
> [00:00.729] ┌获取简介
> [00:00.732] └“我们先死为敬，你们谁敢跟？”地表是核冬天，火星上矗立着一座雄伟城市，但现在一众华夏科学家们，却选择了自爆，只为了将一台生物电脑，送回去……刚刚接受了未来生物电脑的宁为想的却是如何利用学校的规则，靠刷SCI发家致富……“小锤四十，大锤八十”从刷论文开始，宁为挥舞着
> 　　之锤，锤破华夏
> 　　桎梏，改写全球
> 　　格局，这一锤，又值多少？’★重要提示：这是本学霸日常文，不喜日常文慎入……
> [00:00.733] ┌获取封面链接
> [00:00.739] └https://bookcover.yuewen.com/qdbimg/349573/1028469789/180
> [00:00.739] ┌获取详情页链接
> [00:00.746] └https://m.qidian.com/book/1028469789
> [00:00.909] ︽搜索页解析完成
> 
> [00:00.910] ︾开始解析详情页
> [00:01.861] ≡获取成功:https://m.qidian.com/book/1028469789
> [00:01.864] ┌获取书名
> [00:01.866] └科技之锤
> [00:01.866] ┌获取作者
> [00:01.867] └一桶布丁
> [00:01.867] ┌获取分类
> [00:01.870] └
> [00:01.870] ┌获取字数
> [00:01.871] └连载 228.89万字
> [00:01.871] ┌获取最新章节
> [00:01.873] └完本感言
> [00:01.873] ┌获取简介
> [00:01.966] └　　★最近更新:2022-07-04★
> 　　“我们先死为敬，你们谁敢跟？”
> 　　地表是核冬天，火星上矗立着一座雄伟城市，但现在一众华夏科学家们，却选择了自爆，只为了将一台生物电脑，送回去……
> 　　刚刚接受了未来生物电脑的宁为想的却是如何利用学校的规则，靠刷SCI发家致富……
> 　　“小锤四十，大锤八十”
> 　　从刷论文开始，宁为挥舞着科技之锤，锤破华夏科技桎梏，改写全球科技格局，这一锤，又值多少？’
> 　　★重要提示：这是本学霸日常文，不喜日常文慎入……
> [00:01.966] ┌获取封面链接
> [00:01.966] └
> [00:01.967] ┌获取目录链接
> [00:01.979] └https://book.qidian.com/info/1028469789/
> [00:01.980] ︽详情页解析完成
> [00:01.980] ︾开始解析目录页
> 
> [00:02.603] ≡获取成功:https://book.qidian.com/info/1028469789/
> [00:02.609] ┌获取目录列表
> [00:03.858] └列表大小:545
> [00:03.858] ┌解析目录列表
> [00:03.861] ⇒目录0未获取到url,使用baseUrl替代
> [00:03.865] ⇒目录3未获取到url,使用baseUrl替代
> [00:03.915] ⇒目录103未获取到url,使用baseUrl替代
> [00:04.042] └目录列表解析完成
> [00:04.043] ≡首章信息
> [00:04.043] ◇章节名称:📖 [ 作品相关 ] 📖
> [00:04.043] ◇章节链接:https://book.qidian.com/info/1028469789/
> [00:04.043] ◇章节信息:
> [00:04.043] ◇是否VIP:false
> [00:04.043] ◇是否购买:false
> [00:04.047] ◇目录总数:543
> 
> [00:04.053] ︾开始解析正文页
> [00:04.052] ︽目录页解析完成
> [00:04.720] ≡获取成功:https://read.qidian.com/chapter/KhLx6PDdTQDu4xLcYRGW6w2/tR87B6tx3RSaGfXRMrUjdw2/
> [00:04.770] ┌获取章节名称
> [00:04.770] └火星死城 （番外）
> [00:04.770] ┌获取正文内容
> [00:04.770] └
> 　　公元历3398年，二月二十七日，春。
> 　　华夏，K003号地下城。
> ... 省略 ...
> [00:04.772] ︽正文页解析完成
> 
> 调试服务已关闭!
> ```

![Screenshot_20220708_000824_io legado app release](https://user-images.githubusercontent.com/22409452/177821396-5ee4bd8c-043f-4e12-8c3c-11972af31ffb.jpg)
如图，每本书第一时间切换起点必失败，新书必须等再次点击才能获取到目录

**Comment by xiaozixun** [comment]
> 

请问该怎么调出调试日志？如果不难我找个空查一下发出来。

**Comment by xiaozixun** [comment]
> 但我调试书源是正常的。 你描述的这种情况，我无法排查问题。

请问该怎么调出调试日志？如果不难我找个空查一下发出来。

**Comment by XIU2** [comment]
试试我前面用过的搜索词 `科技` 或 `大王饶命`

**Comment by xiaozixun** [comment]
> 试试我前面用过的搜索词 `科技` 或 `大王饶命`

不行，还是那样——第一次搜索必然获取目录失败。

**Comment by XIU2** [comment]
那我就不清楚了，我这边一切正常。

**Comment by xiaozixun** [comment]
> 那我就不清楚了，我这边一切正常。

十分奇怪，只有起点的规则是这样的，我还以为是bug。

**Comment by lostars** [comment]
我也遇到了这个问题，起点大概率获取不到目录，但是调试模式又没有问题

**Comment by lostars** [comment]
![Screenshot_20220711-231041](https://user-images.githubusercontent.com/13404175/178296926-3427a949-0d30-4715-9b4c-5641cb1faa3c.png)
Debug获取到的目录为空

**Comment by XIU2** [comment]
我这边调试正常，无法复现问题的话，我是无法排查并解决的。

**Comment by xiaozixun** [comment]
> 我这边调试正常，无法复现问题的话，我是无法排查并解决的。

`源《起点中文》保存成功！使用搜索关键字“我的”开始调试...`
`[00:00.001] ⇒开始搜索关键字:我的`
`[00:00.002] ︾开始解析搜索页`
`[00:00.622] ≡获取成功:/search?kw=我的`
`[00:00.624] ┌获取书籍列表`
`[00:00.717] └列表大小:10`
`[00:00.720] ┌获取书名`
`[00:00.721] └我的门我的窗`
`[00:00.721] ┌获取作者`
`[00:00.722] └海句子`
`[00:00.722] ┌获取分类`
`[00:00.723] └完结,现代言情`
`[00:00.723] ┌获取字数`
`[00:00.724] └9.67万`
`1.1万`
`[00:00.724] ┌获取最新章节`
`[00:00.725] └第五十节 结局`
`[00:00.725] ┌获取简介`
`[00:00.726] └无论现在如何，总要走一条路通往以后，只是不确定是该打开门走出去，还是从窗户翻出去~`
`[00:00.726] ┌获取封面链接`
`[00:00.728] └https://bookcover.yuewen.com/qdbimg/349573/1003584118/180`
`[00:00.728] ┌获取详情页链接`
`[00:00.730] └https://m.qidian.com/book/1003584118`
`[00:00.800] ︽搜索页解析完成`
`[00:00.801] ︾开始解析详情页`
`[00:01.760] ≡获取成功:https://m.qidian.com/book/1003584118`
`[00:01.761] ┌获取书名`
`[00:01.763] └我的门我的窗`
`[00:01.763] ┌获取作者`
`[00:01.764] └海句子`
`[00:01.764] ┌获取分类`
`[00:01.765] └`
`[00:01.765] ┌获取字数`
`[00:01.766] └完本 9.67万字`
`[00:01.766] ┌获取最新章节`
`[00:01.767] └第五十节 结局`
`[00:01.767] ┌获取简介`
`[00:01.806] └　　★最近更新:2018-05-15★`
`　　无论现在如何，总要走一条 路通往以后，只是不确定是该打开门走出去，还是从窗户翻出去~`
`[00:01.807] ┌获取封面链接`
`[00:01.807] └`
`[00:01.807] ┌获取目录链接`
`[00:01.811] └https://book.qidian.com/info/1003584118/`
`[00:01.812] ︽详情页解析完成`
`[00:01.814] ︾开始解析目录页`
`[00:02.011] ≡获取成功:https://book.qidian.com/info/1003584118/`
`[00:02.012] ┌获取目录列表`
`[00:02.049] └列表大小:0`
`[00:02.052] io.legado.app.exception.TocEmptyException: 目录列表为空`
`调试服务已关闭!`
这是我开了web服务后的东西
话说，这个问题理论上来说应该与手机（系统）无关吧。

**Comment by XIU2** [comment]
@lostars @xiaozixun 我更新书源优化了下，你们更新试试。

**Comment by lostars** [comment]
可以了，感谢大佬更新

**Comment by xiaozixun** [comment]
> @lostars @xiaozixun 我更新书源优化了下，你们更新试试。

没问题了，感谢。
话说如何能像你在2楼那样输入一大段文字（代码）？

**Comment by XIU2** [comment]
用三个 \`\`\` 前后包裹住代码，就是一个代码段了。
具体你去查下 Markdown 语法就知道了，这里回复框右下角就有格式说明链接。
