### ISSUE TITLE
大众无错网 书源失效了

### ISSUE THREAD

**Issue by xiaozixun** [XIU2/Yuedu#46]
大众无错网的搜索地址改了

**Comment by XIU2** [comment]
现有书源中，没有 [大众无错网]。

**Comment by xiaozixun** [comment]
> 现有书源中，没有 [大众无错网]。

抱歉，是大文学无错小说网。

**Comment by XIU2** [comment]
不是搜索地址改了，是这个网站换域名了，我已经更新书源域名了。

**Comment by xiaozixun** [comment]
> 不是搜索地址改了，是这个网站换域名了，我已经更新书源域名了。

好的，谢谢
