### ISSUE TITLE
反馈问题：起点中文 获取目录问题

### ISSUE THREAD

**Issue by xiaozixun** [XIU2/Yuedu#48]
起点的书源在手机上无法读取目录，而在电脑上正常。
版本：legado_app_3.22.080322
书源名称：起点
![Screenshot_20220810_163129_io legado app release](https://user-images.githubusercontent.com/22409452/183856782-eeb7493c-0936-47d4-8f90-8af2b1cdb59e.jpg)

**Comment by XIU2** [comment]
是只有这个书这样，还是全都不行？
《阅读》APP 的 Web 服务功能（即你说的电脑网页版），依然是依靠手机上的《阅读》APP 本身实现调试的，网页只是个 UI。

**Comment by xiaozixun** [comment]
> 是只有这个书这样，还是全都不行？ 《阅读》APP 的 Web 服务功能（即你说的电脑网页版），依然是依靠手机上的《阅读》APP 本身实现调试的，网页只是个 UI。

试了几本都是这样，而且我又发现个古怪问题：似乎在网页上调试过一次，手机上就可以获取目录了（不完全保证是正确的）
现在又能获取目录了

**Comment by XIU2** [comment]
不急，我研究下~

**Comment by XIU2** [comment]
我抽空重写了下 起点 书源，你更新后再试试吧，我这边测试没啥问题了。

我研究尝试了各种书源方案，但都有各种各样的缺点或者无法实现，目前用的这个书源方案，缺点就是读取目录时速度慢，因为用了 AllInOne 正则，章节越多越慢，不过好在《阅读》APP 在获取一次目录后就会缓存下来，后续就没影响了（直到再次刷新目录）。

**Comment by xiaozixun** [comment]
> 我抽空重写了下 起点 书源，你更新后再试试吧，我这边测试没啥问题了。
> 
> 我研究尝试了起点的各种书源方案，但都有各种各样的缺点或者无法实现，目前用的这个书源方案，缺点就是读取目录时速度慢，因为用了 AllInOne 正则，章节越多越慢，不过好在《阅读》APP 在获取一次目录后就会缓存下来，后续就没影响了（直到再次刷新目录）。
> 
> 目前是混合方案，即 搜索页、发现页、正文页 用的是电脑版网页，详情页、目录页 用的是手机版网页，这样省去了频繁用 webView 来加载动态页面导致加载时间过长影响使用体验的问题。
> 
> 唯一不满意的就是目录页只能依靠 AllInOne 正则来匹配，主要是我不清楚如何让《阅读》APP 书源去用 JSONPath 获取网页中的 JSON 对象变量（书源教程太简陋了。。。），否则就完美了，获取目录的速度能快很多。

辛苦了，我试试了，目前没发现问题。
