### ISSUE TITLE
反馈问题：bitbucket分源为乱码

### ISSUE THREAD

**Issue by VoidxHoshi** [XIU2/Yuedu#49]
https://bitbucket.org/xiu2/yuedu/raw/master/shuyuan
此分源中文部分为乱码

**Comment by XIU2** [comment]
不用管，不影响使用。

****

bitbucket 的 raw 网页比较奇葩，会根据文字内容改变网页编码（识别到中文就给改成 GBK 了），而因为文件本身是 UTF-8 编码，所以导致浏览器显示乱码（浏览器将 UTF-8 编码的内容以 GBK 编码显示出来了），但如果你 右键另存为... 将其下载到本地打开的话，就会发现是正常的。

因此不影响导入书源，因为我都测试过了，所以才这么清楚。。。当时还吓我一跳
