### ISSUE TITLE
书源请求:求2.0书源

### ISSUE THREAD

**Issue by zhaibingye** [XIU2/Yuedu#50]
求2.0书源

**Comment by XIU2** [comment]
我很久没用 2.0 了，我现在一直用的就是阅读 3.0 版本，因此我只会写 3.0 的书源。
我写的书源都是我自用的，因此我用什么我才会写什么，这个项目只是我分享自用书源的地方。

**Comment by zhaibingye** [comment]
> 

好的谢谢,看来我这样的2.0老古董也是时候该放弃了

**Comment by XIU2** [comment]
毕竟 2.0 -> 3.0 关于书源部分改动较大，2.0 的书源可以转换为 3.0 的，但是 3.0 的书源基本上是无法转换为 2.0 了，因为很多功能 2.0 不支持。
