### ISSUE TITLE
书源请求：添加燃文小说

### ISSUE THREAD

**Issue by xiaozixun** [XIU2/Yuedu#52]
URL：www.ranwen.la或m.www.ranwen.la

**Comment by XIU2** [comment]
“并写出推荐原因”，写书源很费时间，没有特别必要的话，我是懒得费劲去写的。

**Comment by xiaozixun** [comment]
> “并写出推荐原因”，写书源很费时间，没有特别必要的话，我是懒得费劲去写的。

这网站里有一本正好是我追的书在更新
（或者能教下我该怎么写书源吗？）

**Comment by XIU2** [comment]
我这里目前所有书源，都找不到你看的书吗？
****
这我怎么教你？毕竟不是几分钟能速成的。。。
需要对网页前端（HTML + CSS）有一些基础 与 了解，对于常规网页的书源，本质上就是分析网页结构，提取书源需要的地方特征，让阅读 APP 知道怎么获取其需要的内容。

**Comment by xiaozixun** [comment]
> 我这里目前所有书源，都找不到你看的书吗？
> 
> 这我怎么教你？毕竟不是几分钟能速成的。。。 需要对网页前端（HTML + CSS）有一些基础 与 了解，对于常规网页的书源，本质上就是分析网页结构，提取书源需要的地方特征，让阅读 APP 知道怎么获取其需要的内容。

抱歉，我又看了看原来是没更新书源，这下可以了。怪我，这个可以关了
> 
好吧，我以为能简单的速成下，最近时间不太多，学不了太多东西。
