### ISSUE TITLE
反馈问题：口袋阅读的一个小问题

### ISSUE THREAD

**Issue by xiaozixun** [XIU2/Yuedu#53]
### 阅读版本（我的 - 关于 - 版本，如 3.20.112220）
> 3.22.080322

### 书源名称
> 口袋阅读

### 问题描述（最好写上 复现步骤，特别是一些复杂的问题）
> 它没有失效，只是会有几本无法获取到最新章节的正文，我看调试里也是正常的。不知道是什么原因？

**Comment by XIU2** [comment]
这个书源不是我写的，是别人推荐给我的，而且该书源经过了加密，我也无从下手。。。
