### ISSUE TITLE
反馈问题：口袋阅读报错啦，请大佬修复一下

### ISSUE THREAD

**Issue by SJJ-dot** [XIU2/Yuedu#58]
阅读版本
3.22

口袋阅读报错啦，请大佬修复一下

**Comment by XIU2** [comment]
该书源不是我写的，是别人推荐给我的，是个 API 书源，我无法修复。

**Comment by XIU2** [comment]
解密后排查了下，并不是书源的问题，而是该 API 接口变了，估计是用的人太多被 QQ 发现了。

**Comment by SJJ-dot** [comment]
> 接口变了，估计是用的人太多被 QQ 发现了。

好吧
