### ISSUE TITLE
反馈问题：爱好中文网不显示最新章节，且在书架页下拉刷新最新章节特别慢

### ISSUE THREAD

**Issue by marujun** [XIU2/Yuedu#61]
### 阅读版本
> 3.22.100921

### 书源名称
> 爱好中文网

### 问题描述
![Screenshot_2022-10-11-11-18-45-299-edit_io legado app release](https://user-images.githubusercontent.com/1955015/194990498-64348015-c43a-4a40-8851-aa2ff2779feb.jpg )
> 截图中的书籍： https://m.ah123z.com/book/9702/
> 复现步骤：
> 1. 不显示最新章节：添加书籍之后，点到书籍某个章节然后切换书源，点击刷新之后发现不显示最新章节如上图所示
> 2. 特别慢：把这本书添加到书架中，然后下拉刷新，会发现最新章节出现的特别慢，比其他源至少慢了4~5倍

怀疑是不是因为没有配置最新章节获取规则导致的？

**Comment by XIU2** [comment]
因为该网站的搜索页压根没有 最新章节 信息，所以这类网站，都会显示为 无最新章节。
你可以在右上角三个点里勾选 [加载详情页]、[加载目录] 应该就能显示出来 最新章节 了。
