### ISSUE TITLE
书源请求：一起看大文学小说网

### ISSUE THREAD

**Issue by fengsj2000** [XIU2/Yuedu#62]
### 小说网站 的 地址
> https://www.wcxsw.org/

### 特别推荐 的 原因
> 起点小说大部分都有更新，且不是防盗贴

**Comment by XIU2** [comment]
你是不是压根没用我的书源就来提 Issues 了？
这网站我早就添加支持了！

https://github.com/XIU2/Yuedu/blob/f8f33e9ac20ec45a890f1d6d15deb849cc813214/shuyuan#L1032-L1034

**Comment by fengsj2000** [comment]
> 你是不是压根没用我的书源就来提 Issues 了？ 这网站我早就添加支持了！ #32 #46
> 
> https://github.com/XIU2/Yuedu/blob/f8f33e9ac20ec45a890f1d6d15deb849cc813214/shuyuan#L1032-L1034

用过书源，可是一直搜索失败才找过来的_(:з」∠)_

**Comment by fengsj2000** [comment]
阅读3.0，版本号3.22.102918，一直用的"大文学"，换域名后也用了几天，结果这两三天以来一直提示自动换源，点击手动换源时，也无法在可用源里找到"大文学无错小说网"。但是电脑上"https://www.wcxsw.org"明明都是有更新的啊？

**Comment by XIU2** [comment]
#63 #59

**Comment by XIU2** [comment]
你更新书源，改用我新加的 `大文学无错小说网 - 手机版` 吧。

**Comment by fengsj2000** [comment]
哇，大人最棒了，就指着这个书源看书了(✧◡✧)


--------------------------------
AmyFeng

----- Original Message -----
From: XIU2 ***@***.***>
To: XIU2/Yuedu ***@***.***>
Cc: fengsj2000 ***@***.***>,  Author ***@***.***>
Subject: Re:_[XIU2/Yuedu]_书源请求：一起看大文学小说网_(Issue_#62)
Date: 2022-10-30 15:24



你更新书源，改用我新加的 大文学无错小说网 - 手机版 吧。
