### ISSUE TITLE
书源请求：全本小说网

### ISSUE THREAD

**Issue by sailangyf** [XIU2/Yuedu#65]
### 小说网站 的 地址
> https://http://www.fxtom.com/

### 特别推荐 的 原因
> 网站本身是难得的清新无广告，最厉害的是有些出版小说都能搜到（例如：矢野浩二-有梦不怕路远，微信读书都看不了），可以很好的与其他书源互补。

**Comment by XIU2** [comment]
你管这叫 “清新无广告” ？
为什么我随便点哪本小说，进去正文全都是广告。。。

我特么书源都快写完了，测试时才发现，这特么正文都是什么鬼？浪费我时间。
![01](https://user-images.githubusercontent.com/54703944/201507062-da2e01c8-25c2-49a6-9e3b-0d45c1b048c4.png)

**Comment by sailangyf** [comment]
大佬非常抱歉，因为一本出版书籍我找了很久都没有找到然后在这个网站找到了，当时看挺好的，而且也没有乱七八糟的弹窗，就发出来了，没有仔细审核，非常抱歉，耽误你的时间啦，非常抱歉。
