### ISSUE TITLE
反馈问题：番茄小说 书源存在问题

### ISSUE THREAD

**Issue by miangou** [XIU2/Yuedu#66]
后续章节无法观看

**Comment by miangou** [comment]
http://shuyuan.miaogongzi.net/shuyuan/1668555228.json
的书源正常

**Comment by XIU2** [comment]
看起来这个 API 源好像失效了，我收录了你给的这个番茄小说书源，暂时将其替代了。

**Comment by miangou** [comment]
[bookSource-2022-12-03.json.zip](https://github.com/XIU2/Yuedu/files/10148303/bookSource-2022-12-03.json.zip)
