### ISSUE TITLE
能否在书源中增加这本书

### ISSUE THREAD

**Issue by discusssth** [XIU2/yuedu#7]
![image](https://user-images.githubusercontent.com/45059308/89376467-63b6b680-d722-11ea-8d48-8de67d471e27.png)

http://www.biquge.info/53_53780/

**### 谢谢**

**Comment by XIU2** [comment]
书源并不是我制作的，我只是收集一下并每天更新而已。
另外这本书我搜了下，是可以搜到的呀。
