### ISSUE TITLE
有人知道legado有第三方Windows版本么

### ISSUE THREAD

**Issue by aalaaiaanaa** [XIU2/Yuedu#72]
Att

**Comment by XIU2** [comment]
不清楚。

你可以手机阅读 APP 上打开 WEB 选项，这样你电脑可以通过网页链接手机上的阅读 APP，来阅读小说。

或者，你可以在服务器上搭建一个阅读网页版。
https://github.com/hectorqin/reader

最后，我只想说这种问题，你应该去阅读 APP 官方项目询问，而不是问我这个使用者。
https://github.com/gedoor/legado
