### ISSUE TITLE
书源请求：乐文小说网

### ISSUE THREAD

**Issue by GithubMoshu** [XIU2/Yuedu#73]
### 小说网站 的 地址
> https://www.365xs.la/

### 特别推荐 的 原因
> [开发大西北：我在戈壁建了一座城] 之前用书源切换了好多书源都没有最新章节更新，或者说只更新了章节名，内容都没有，这个竟然有内容，也看了下其它书，确实不错。推荐一下。

**Comment by XIU2** [comment]
已更新添加支持。
