### ISSUE TITLE
想要修改返回目录

### ISSUE THREAD

**Issue by Codebglh** [XIU2/Yuedu#74]
`//*[@id="content"]/table/tbody/tr{
(  function(result){
          for (var i=1;i<result.length;i++){
          let list[i-1]=result[i]
    }
          return list;
 })(result);}`
这样写不能修改返回目录
https://www.shuquzw.la/modules/article/search.php,{
  "method": "POST",
  "body": "searchkey={{key}}"
}

**Comment by XIU2** [comment]
啥？没明白你要表达什么意思。。。
