### ISSUE TITLE
书源请求：铅笔小说网

### ISSUE THREAD

**Issue by KasuganoAsahi** [XIU2/Yuedu#76]
### 网站地址

https://www.23qb.com

### 推荐原因

老牌且稳定的小说网站,更新快速及时,收录范围也很广,且有速度更新非常快的轻小说,如果能支持就太棒了,谢谢🙏

**Comment by XIU2** [comment]
我以前写过一个铅笔小说的书源，虽然是 .net 的但和 .com 是同一个网站（这网站好几个域名），不过缺点就是**要搜索的话必须先登录**（注册账号的话很简单，邮箱也可以随便填，反正也不验证），否则就只能去发现里找书了。

> 你需要先去书源管理，找到 `铅笔小说` 点击右侧的三个点按钮，选择 `登录` 会打开网站的登录页面，登录成功后点击右上角的 `√` 保存即可，这样就能用该书源搜索了。

我找了找，测试了下没啥问题，不过因为该网站会对一些单章字数较多的进行分页，分页可能会把一句话断开，软件合并多个分页后可能会看到这样的情况：

>　　苏龙咧嘴笑呵呵道：“你要是没成年，爸不会走！可现在，我得回去，18年前我那个队，还有几个和你一样大的小子，阿宇，你知道吗？我做梦了，梦到他们了……梦里哭着喊着说好疼，说杀光那群畜生，你爸
>　　我有点后悔了，当年……就该把你送到军属院，反正也有人养你。”


```
{
    "bookSourceComment": "需要登录后才能搜索，备用 https://www.23qb.com",
    "bookSourceGroup": "",
    "bookSourceName": "铅笔小说",
    "bookSourceType": 0,
    "bookSourceUrl": "https://www.23qb.net",
    "bookUrlPattern": "",
    "customOrder": 58,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "enabledReview": false,
    "exploreUrl": "最近更新::/book/0-lastupdate-0-0-0-0-0-0-{{page}}.html\n最新入库::/book/0-postdate-0-0-0-0-0-0-{{page}}.html\n总点击榜::/book/0-allvisit-0-0-0-0-0-0-{{page}}.html\n总推荐榜::/book/0-allvote-0-0-0-0-0-0-{{page}}.html\n总收藏榜::/book/0-goodnum-0-0-0-0-0-0-{{page}}.html\n总字数榜::/book/0-size-0-0-0-0-0-0-{{page}}.html\n完本小说::/book/0-quanben-0-0-0-0-2-0-{{page}}.html\n全部小说::/book/0-quanben-0-0-0-0-0-0-{{page}}.html\n言情女生::/yanqing/<,{{page}}>\n玄幻奇幻::/xuanhuan/<,{{page}}>\n都市青春::/dushi/<,{{page}}>\n武侠仙侠::/wuxia/<,{{page}}>\n唯美纯爱::/danmei/<,{{page}}>\n科幻灵异::/kehuan/<,{{page}}>\n轻小说の::/lightnovel/<,{{page}}>\n历史军事::/lishi/<,{{page}}>",
    "lastUpdateTime": 1680914529004,
    "loginUrl": "https://www.23qb.net/login.php",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": "//meta[@property='og:novel:author']/@content",
        "coverUrl": "//meta[@property='og:image']/@content",
        "intro": "//meta[@property='og:description']/@content",
        "kind": "//meta[@property='og:novel:category']/@content",
        "lastChapter": "//meta[@property='og:novel:latest_chapter_name']/@content",
        "name": "//meta[@property='og:novel:book_name']/@content"
    },
    "ruleContent": {
        "content": "id.TextContent@tag.p@html##23qb.net",
        "nextContentUrl": "##nextpage=\"([^\"]+)\"##$1###",
        "replaceRegex": "##铅笔小说|\\s*（继续下一页）\\s*",
        "webJs": "##nextpage=\"([^\"]+)\"##$1###"
    },
    "ruleSearch": {
        "author": ".book_other@span.0@text",
        "bookList": "id.sitebox@dl",
        "bookUrl": "a@href",
        "coverUrl": "img@_src",
        "intro": ".book_des@text",
        "kind": "tag.span.0@text&&tag.span.3@text",
        "lastChapter": "class.book_other.1@a@text",
        "name": "h3@a@text",
        "wordCount": "class.book_other.0@tag.span.2@text"
    },
    "ruleToc": {
        "chapterList": "class.chaw_c@li@a",
        "chapterName": "text",
        "chapterUrl": "href"
    },
    "searchUrl": "https://www.23qb.net/saerch.php,{\"charset\": \"gbk\",\"method\": \"POST\",\"body\": \"searchkey={{key}}&page={{page}}&searchtype=all\"}",
    "weight": 0
}
```

**Comment by KasuganoAsahi** [comment]
感谢回复,我原来是用您发布的二维码添加的65个书源,里面没有铅笔小说,请问是需要单独添加吗?该如何添加呢?


| |
贾辰
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年04月8日 08:51 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [XIU2/Yuedu] 书源请求：铅笔小说网 (Issue #76) |

Closed #76 as completed.

**Comment by KasuganoAsahi** [comment]
https://raw.iqiq.io/XIU2/Yuedu/master/shuyuan,我是从这里添加的书源 



| |
贾辰
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年04月8日 08:51 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [XIU2/Yuedu] 书源请求：铅笔小说网 (Issue #76) |

Closed #76 as completed.

**Comment by XIU2** [comment]
新建一个空白文本文件，复制这段书源到文件内，修改文件名为 `1.json`（名字无所谓，主要是文件后缀需要是 `.json`）
> 如果你是在电脑上操作的话，那么就把该文件放到手机里

然后在阅读 `书源管理` 中点击右上角的三个点，选择 `本地导入`，选择该文件即可。

**Comment by KasuganoAsahi** [comment]
明白了,好的太感谢啦!

**Comment by KasuganoAsahi** [comment]
您好,上次关于铅笔小说书源的问题,我发现一个问题
就是编辑书源里的“发现”,也就是网站list页,只能拉取第一页的数据,然后就显示到底了,如何才能翻页拉取列表数据呢?


| |
贾辰
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年04月8日 11:30 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [XIU2/Yuedu] 书源请求：铅笔小说网 (Issue #76) |

新建一个空白文本文件，复制这段书源到文件内，修改文件名为 1.json（名字无所谓，主要是文件后缀需要是 .json）

如果你是在电脑上操作的话，那么就把该文件放到手机里

然后在阅读 书源管理 中点击右上角的三个点，选择 本地导入，选择该文件即可。

**Comment by XIU2** [comment]
已修复

``` json
{
    "bookSourceComment": "需要在书源管理中登录后才能搜索，备用 https://www.23qb.com",
    "bookSourceGroup": "",
    "bookSourceName": "铅笔小说",
    "bookSourceType": 0,
    "bookSourceUrl": "https://www.23qb.net",
    "bookUrlPattern": "",
    "customOrder": 58,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "enabledReview": false,
    "exploreUrl": "最近更新::/book/0-lastupdate-0-0-0-0-0-0-{{page}}.html\n最新入库::/book/0-postdate-0-0-0-0-0-0-{{page}}.html\n总点击榜::/book/0-allvisit-0-0-0-0-0-0-{{page}}.html\n总推荐榜::/book/0-allvote-0-0-0-0-0-0-{{page}}.html\n总收藏榜::/book/0-goodnum-0-0-0-0-0-0-{{page}}.html\n总字数榜::/book/0-size-0-0-0-0-0-0-{{page}}.html\n完本小说::/book/0-quanben-0-0-0-0-2-0-{{page}}.html\n全部小说::/book/0-quanben-0-0-0-0-0-0-{{page}}.html\n言情女生::/yanqing/{{page}}/\n玄幻奇幻::/xuanhuan/{{page}}/\n都市青春::/dushi/{{page}}/\n武侠仙侠::/wuxia/{{page}}/\n唯美纯爱::/danmei/{{page}}/\n科幻灵异::/kehuan/{{page}}/\n轻小说の::/lightnovel/{{page}}/\n历史军事::/lishi/{{page}}/",
    "lastUpdateTime": 1681883680332,
    "loginUrl": "https://www.23qb.net/login.php",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": "//meta[@property='og:novel:author']/@content",
        "coverUrl": "//meta[@property='og:image']/@content",
        "intro": "//meta[@property='og:description']/@content",
        "kind": "//meta[@property='og:novel:category']/@content",
        "lastChapter": "//meta[@property='og:novel:latest_chapter_name']/@content",
        "name": "//meta[@property='og:novel:book_name']/@content"
    },
    "ruleContent": {
        "content": "id.TextContent@tag.p@html##23qb.net",
        "nextContentUrl": "##nextpage=\"([^\"]+)\"##$1###",
        "replaceRegex": "##铅笔小说|\\s*（继续下一页）\\s*",
        "webJs": "##nextpage=\"([^\"]+)\"##$1###"
    },
    "ruleSearch": {
        "author": ".book_other@span.0@text",
        "bookList": "id.sitebox@dl",
        "bookUrl": "a@href",
        "coverUrl": "img@_src",
        "intro": ".book_des@text",
        "kind": "tag.span.0@text&&tag.span.3@text",
        "lastChapter": "class.book_other.1@a@text",
        "name": "h3@a@text",
        "wordCount": "class.book_other.0@tag.span.2@text"
    },
    "ruleToc": {
        "chapterList": "class.chaw_c@li@a",
        "chapterName": "text",
        "chapterUrl": "href"
    },
    "searchUrl": "https://www.23qb.net/saerch.php,{\"charset\": \"gbk\",\"method\": \"POST\",\"body\": \"searchkey={{key}}&page={{page}}&searchtype=all\"}",
    "weight": 0
}
```

**Comment by KasuganoAsahi** [comment]
谢谢,这回的完美了,太感谢了🙏


| |
贾辰
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年04月19日 13:55 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [XIU2/Yuedu] 书源请求：铅笔小说网 (Issue #76) |

已修复

{
    "bookSourceComment": "需要在书源管理中登录后才能搜索，备用 https://www.23qb.com",
    "bookSourceGroup": "",
    "bookSourceName": "铅笔小说",
    "bookSourceType": 0,
    "bookSourceUrl": "https://www.23qb.net",
    "bookUrlPattern": "",
    "customOrder": 58,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "enabledReview": false,
    "exploreUrl": "最近更新::/book/0-lastupdate-0-0-0-0-0-0-{{page}}.html\n最新入库::/book/0-postdate-0-0-0-0-0-0-{{page}}.html\n总点击榜::/book/0-allvisit-0-0-0-0-0-0-{{page}}.html\n总推荐榜::/book/0-allvote-0-0-0-0-0-0-{{page}}.html\n总收藏榜::/book/0-goodnum-0-0-0-0-0-0-{{page}}.html\n总字数榜::/book/0-size-0-0-0-0-0-0-{{page}}.html\n完本小说::/book/0-quanben-0-0-0-0-2-0-{{page}}.html\n全部小说::/book/0-quanben-0-0-0-0-0-0-{{page}}.html\n言情女生::/yanqing/{{page}}/\n玄幻奇幻::/xuanhuan/{{page}}/\n都市青春::/dushi/{{page}}/\n武侠仙侠::/wuxia/{{page}}/\n唯美纯爱::/danmei/{{page}}/\n科幻灵异::/kehuan/{{page}}/\n轻小说の::/lightnovel/{{page}}/\n历史军事::/lishi/{{page}}/",
    "lastUpdateTime": 1681883680332,
    "loginUrl": "https://www.23qb.net/login.php",
    "respondTime": 180000,
    "ruleBookInfo": {
        "author": ***@***.******@***.***",
        "coverUrl": ***@***.******@***.***",
        "intro": ***@***.******@***.***",
        "kind": ***@***.******@***.***",
        "lastChapter": ***@***.******@***.***",
        "name": ***@***.******@***.***"
    },
    "ruleContent": {
        "content": ***@***.***@html##23qb.net",
        "nextContentUrl": "##nextpage=\"([^\"]+)\"##$1###",
        "replaceRegex": "##铅笔小说|\\s*（继续下一页）\\s*",
        "webJs": "##nextpage=\"([^\"]+)\"##$1###"
    },
    "ruleSearch": {
        "author": ***@***.***@text",
        "bookList": ***@***.***",
        "bookUrl": ***@***.***",
        "coverUrl": "img@_src",
        "intro": ***@***.***",
        "kind": ***@***.******@***.***",
        "lastChapter": ***@***.***@text",
        "name": ***@***.***@text",
        "wordCount": ***@***.***@text"
    },
    "ruleToc": {
        "chapterList": ***@***.***@a",
        "chapterName": "text",
        "chapterUrl": "href"
    },
    "searchUrl": "https://www.23qb.net/saerch.php,{\"charset\": \"gbk\",\"method\": \"POST\",\"body\": \"searchkey={{key}}&page={{page}}&searchtype=all\"}",
    "weight": 0
}
