### ISSUE TITLE
反馈问题：口袋阅读 书源失效

### ISSUE THREAD

**Issue by BadDeveloper2022** [XIU2/Yuedu#78]
### 阅读版本

全部版本

### 书源名称

口袋阅读

### 问题描述

接口失效，content 字段返回空

### 附加截图

![image](https://user-images.githubusercontent.com/7404699/233817805-a6ff8b59-c55f-430d-b9a7-a3d87ff60986.png)

**Comment by XIU2** [comment]
该 API 书源不是我写的，失效后无法修复。

**Comment by BadDeveloper2022** [comment]
ok
