### ISSUE TITLE
反馈问题：笔趣阁 书源正文标题出现乱码

### ISSUE THREAD

**Issue by czm180** [XIU2/Yuedu#79]
### 阅读版本

3.23.040420

### 书源名称

笔趣阁

### 问题描述

阅读时标题出现乱码，但正文无影响

**Comment by SherkeyXD** [comment]
同 ![Screenshot_2023-05-21-02-48-53-056_io.legado.app.release.jpg](https://github.com/XIU2/Yuedu/assets/57581480/4d67c391-28e2-494b-a1db-717d20eec0f4)

**Comment by XIU2** [comment]
说的“乱码”原来指的是这个啊，这不是乱码，而是被加密了（基于 Base64 但并不单单是这个，因此在不知道 key 的情况下是无法解密的），因此该问题无法修复。
