### ISSUE TITLE
笔趣阁 mibaoge错误

### ISSUE THREAD

**Issue by cyao2q** [XIU2/yuedu#8]
用搜书大师的时候有这个笔趣阁 mibaoge挺好用 发现你写的也有但就是搜索不到东西。去官网看了下搜索URL错误了
https://www.mibaoge.com/search.php?keyword={{key}}
换成
https://www.mibaoge.com/search.php?q={{key}}

希望抽空改下

**Comment by XIU2** [comment]
已经修改了。
这个项目里只有一部分书源是我写的，另外的大部分都是阅读APP作者分享的。
你说的这个就是作者分享的，我改了改更新脚本，跳过了这个，把这个书源单独拎出来改了改。
