### ISSUE TITLE
书源请求：藏海花小说网

### ISSUE THREAD

**Issue by nscmiaoxin** [XIU2/Yuedu#88]
### 网站地址

https://www.zanghaihua.org/

### 推荐原因

1. 比如耳东水寿的《天黑请下凡》，藏海花小说网更新的非常勤快，而且质量不错；
2. 整个网址对悬疑、探险类小说的收录比较全，比较垂直；
3. 错别字少，效果不错；
希望大神考虑收录，感谢感谢！

**Comment by XIU2** [comment]
该网站好像无法搜索，搜索任何关键词、书名都会报错 405 。
搜索是一个书源的核心，无法搜索意味着书源无法搜索、无法换源等。

**Comment by nscmiaoxin** [comment]
> 该网站好像无法搜索，搜索任何关键词、书名都会报错 405 。 搜索是一个书源的核心，无法搜索意味着书源无法进行搜索、换源等核心操作，这种无法搜索的网站做成书源的话，使用起来会很麻烦，只能通过发现来添加书，或者在网页里找到书后，手动添加书籍详情页 URL 才行。
> 
> 看了下，该网站的搜索框表单元素，压根没有指定搜索接口的目标地址。

明白了，谢谢大神解惑，感谢，另外反馈一下，69书吧好像还是不怎么稳定，时不时刷不出来。

**Comment by XIU2** [comment]
你说的 `69 书吧` 的问题我没有遇到，可能是我在线小说看的比较少吧（书架里基本都是完本的本地小说）。
`69 书吧` 里用的地址都是 `69 书吧` 自己的，如果出现不稳定要么就是这网站问题，要么就是你那边网络问题，这些我都无法解决。
