### ISSUE TITLE
反馈问题：69书吧 书源一些正文第一行没有章节名导致第一行正文内容被删除

### ISSUE THREAD

**Issue by f7time** [XIU2/Yuedu#89]
### 阅读版本

3.23.062623

### 书源名称

69书吧

### 问题描述

读取内容删减问题。这网站没统一，每一话文章内容时有标题时没有。为了美观把重复标题删了，造成没标题的少了第一段句子。

### 附加截图

![Screenshot_20230728_113101_com microsoft emmx](https://github.com/XIU2/Yuedu/assets/140779761/06a9d4f3-3a1c-4f27-8aad-fb07e56311a3)
![Screenshot_20230728_113106_io legado app release](https://github.com/XIU2/Yuedu/assets/140779761/db4c0a7b-15d4-4602-96f3-c0eb41d6810e)
![Screenshot_20230728_105036_com microsoft emmx](https://github.com/XIU2/Yuedu/assets/140779761/a97014b7-7358-410e-a0ce-7443471c0e25)
![Screenshot_20230728_105216_io legado app release](https://github.com/XIU2/Yuedu/assets/140779761/a8dbb671-7863-4bb8-b6ba-37b2382ef44e)

**Comment by XIU2** [comment]
那这个就难解决了，因为我之所以是直接移除第一行而不是匹配第一行的第X章再移除，是因为一些章节正文第一行并不是 第X章 格式的，有些甚至是乱七八糟的毫无规律，因此无法通过正则匹配来完美净化第一行。

**Comment by XIU2** [comment]
你要是想要自行通过净化规则解决，那么你可以修改书源，把 正文 的替换规则改为：`##(\(本章完\)$)`

**Comment by XIU2** [comment]
突然想起来 阅读 是有内置变量的，我查了查，改了改，这回应该可以完美净化了。

把 正文 的替换规则改为：
```
##(^　　{{book.durChapterTitle}}.*)|(\(本章完\)$)
```
这样就只会屏蔽正文开头的第一行的 当前章节名称，对于正文第一行不是章节名称的则不会有影响。

你可以用这两个目录页调试一下看看效果：
```
++https://d34xj6zzll2cc7.cloudfront.net/A43616/
++https://d34xj6zzll2cc7.cloudfront.net/10046534/
```

> 注意，不能直接用正文页调试，因为这样的话阅读是不知道当前章节名称的，必须要用目录页、详情页、搜索页等调试才行。

**Comment by XIU2** [comment]
另外，我也注意到你截图里的 `www.69shuba.com`，看了下以为是镜像站，又好像是官方的镜像站，但测了下好像有些地方比较奇怪，单纯替换域名的话，一些书籍详情页会提示 404（而一些书籍的又会被重定向到该域名），搞不明白，但因为这个原因也无法完全替代 `www.69shu.com` 主域名使用，所以我的书源也就不改动了。

另外，上面这个正文净化规则的改动，我已经更新书源了。
