### ISSUE TITLE
反馈问题：69 书吧 书源搜索失效

### ISSUE THREAD

**Issue by keai-1989** [XIU2/Yuedu#91]
### 阅读版本

69书吧连不上了

### 书源名称

灵境行者

### 问题描述

69书吧连不上了，搜索，调试里也试了，镜像站能打开，但无法搜索，后缀连书籍地址也无法打开网站

**Comment by XIU2** [comment]
这是 69 书吧 网站官方的问题，无论是这个 `d34xj6zzll2cc7.cloudfront.net` 还主域名 `www.69shu.com` 去搜索都会报错 401 。

**Comment by Sisyphean-a** [comment]
1. 这个69书吧使用的是post请求，阅读目前只能使用get请求搜索
```http
POST https://www.69shuba.com/modules/article/search.php
Content-Type: application/x-www-form-urlencoded
Referer: https://www.69shuba.com/

searchkey=%D2%FE%C3%D8&submit=Search
```
2. 不知道编码规则，上面的searchkey的值是"隐秘"，不知道是怎么转换成的"%D2%FE%C3%D8"

**Comment by XIU2** [comment]
@Sisyphean-a 

1. 谁跟你说 阅读 只能发起 GET 请求搜索的？。。。
2. searchkey 搜索关键词都是要 URL 加密后传输的，这个阅读自己会处理，只需要注意网页编码即可。

**Comment by lshilshi** [comment]
> @Sisyphean-a
> 
> 1. 谁跟你说 阅读 只能发起 GET 请求搜索的？。。。
> 2. searchkey 搜索关键词都是要 URL 加密后传输的，这个阅读自己会处理，只需要注意网页编码即可。

好像，69shu换原来的备用网址了，https://www.69shuba.com。
现在书源不能搜索，但是已添加书籍还是可以更新的。而源站现在可以搜索了，请更新！

**Comment by Sisyphean-a** [comment]
> @Sisyphean-a
> 
> 1. 谁说读完才能发起GET请求搜索的？。。。
> 2. searchkey关键词搜索都是要URL加密后传输的，这个阅读自己会处理，只需要注意网页编码即可。

感谢指正！
之前误以为只能阅读只能发送get请求
然后我尝试了一下，之前默认以为utf-8加密，网页编码设置成gbk之后确实可以正确加密

**Comment by XIU2** [comment]
@lshilshi 无论是 `d34xj6zzll2cc7.cloudfront.net` 还主域名 `www.69shu.com` 现在都会重定向到 `www.69shuba.com` 但这个域名下搜索都会报错 401 。

所以你说的 "而源站现在可以搜索了" 是什么意思？

**Comment by lshilshi** [comment]
> @lshilshi 无论是 `d34xj6zzll2cc7.cloudfront.net` 还主域名 `www.69shu.com` 现在都会重定向到 `www.69shuba.com` 但这个域名下搜索都会报错 401 。
> 
> 所以你说的 "而源站现在可以搜索了" 是什么意思？

我挂T在www.69shuba.com是可以正常搜索的，看基安里面讨论，好像在3,4天前，也就是主域名 `www.69shu.com` 重定向到 `www.69shuba.com` 后，搜索就正常了

直接修改书源里面的origin/referer中的 `www.69shu.com` 为`www.69shuba.com` ，还是失效的
所以还是来麻烦大拿了，辛苦！

**Comment by XIU2** [comment]
@lshilshi 如果需要挂代理访问这个没有被墙的域名才能搜索，那么这个就没有意义了。

我写这个书源就是为了实现直连完美访问的。

**Comment by XIU2** [comment]
我又研究了下，感觉这网站好像是故意禁止了国内 IP 进行搜索。

尝试伪造了下头部 `x-forwarded-for` 没啥用，只能走国内的代理才能搜索。

我能想到的解决方法就是在国外服务器上建一个反代（只匹配搜索 URL 地址即可），然后书源里的搜索地址改成这个反代地址。  
> Cloudflare 的免费 Worker 也行，限制每天 10 万次（当然，因为是反代的原因，所以访问一次算为 2 次），个人用是肯定够了，但是做成书源分享出来怕是很快就 G 了。

**Comment by lshilshi** [comment]
> 

worker倒是有，在之前做GAE XX-Net代理时用过
要是可以，可以不内置，出个教程，指导如果操作，八仙过海自己建好了

**Comment by lshilshi** [comment]
> Worker 默认分配的免费域名不行，因为被墙了

谢谢分享！
不过“Worker 默认分配的免费域名不行，因为被墙了”，一下就干掉我了，我没购买域名，使用的就是worker默认的免费域名，那等于还是不能用，和挂墙没区别

ps:就是配置好了合适的worker反代
我看书源虽然搜索用的是反代域名，但是搜完之后，后面更新目录、拉取新章节都是走的69shuba.com这个吧
这个还是被墙（限制大陆IP访问？），等于日常更新还是需要挂T的吧
那反代意义也就剩一个搜索用了

**Comment by XIU2** [comment]
@lshilshi `www.69shuba.com` 没有被墙，只是搜索功能限制了国内 IP（这也是我根据简单测试所猜测的，也可能是其他原因），其他页面、看书阅读啥的国内都可以直接访问，没有任何问题。

我写上面教程的时候，就是自己建了一个 Worker，并且自己调试过书源，确保 Worker 代码和书源都没有问题，无论是搜索关键词还是搜索完整书名（会重定向到详情页），各种页面解析均一切正常。

**Comment by cxumol** [comment]
https://github.com/XIU2/Yuedu/issues/91#issuecomment-1687579537 海外 IP 删掉 "searchUrl" 的 `https://XXXXXXXXXX` 后可用, 感谢｡ 
如果从本 git 库当前书源基础上修改, 改 "bookSourceUrl" ､ "searchUrl" 两段即可

**Comment by lshilshi** [comment]
> @lshilshi `www.69shuba.com` 没有被墙，只是搜索功能限制了国内 IP（这也是我根据简单测试所猜测的，也可能是其他原因），其他页面、看书阅读啥的国内都可以直接访问，没有任何问题。
> 
> 我写上面教程的时候，就是自己建了一个 Worker，并且自己调试过书源，确保 Worker 代码和书源都没有问题，无论是搜索关键词还是搜索完整书名（会重定向到详情页），各种页面解析均一切正常。

现在69shuba（从8.30日中午起）被墙/主动屏蔽大陆IP了
又回到挂T的时代了

**Comment by lshilshi** [comment]
> @lshilshi 我看了下，`www.69shuba.com` 并没有被 DNS 污染，而是全站主动屏蔽大陆 IP 了。 搞不懂站长咋想的。。。
> 
> 所以现在要么挂代理，要么自建镜像（Worker 也可以），不过对我影响不大，因为我现在书架里基本上都是完本的本地小说。

正在申请eu.org的免费域名，等到手了就绑到worker去
不过你前面的worker代码还能用吗？
因为原来只是搜索用反代，现在是全站都屏蔽了大陆IP
等于搜索完了，日常加载目录/获取正文都是不行的

**Comment by XIU2** [comment]
@lshilshi 前面的 Worker 代码仅针对搜索页，所以自然不能直接用了，你可以去搜搜别人开源的反向代理 Worker 代码去用，或者问 GPT 要，我对这网站没啥兴趣（因为我基本不追连载小说，都是本地的完本小说），懒得费劲折腾这些了，毕竟镜像只能自用不能公开。
