### ISSUE TITLE
书源请求：苏明小说网

### ISSUE THREAD

**Issue by xiaowonet** [XIU2/Yuedu#94]
### 网站地址

https://sumingxs.com/

### 推荐原因

《宿命之环》小说在其他所有书源中，都有许多错别字，甚至缺少整句话，这个小说网站，是我看过错别字最少，也没有漏句的。

举例：
第一卷 第一百零八章 报告
“我们确定了三件事情”后面，其他书源都漏了一句话，此网站没有漏。

第一卷第一百零九章 微小的希望
“留着小胡子的男人顿时有了谈兴”后面，其他书源都漏了一句话，此网站没有漏。

**Comment by XIU2** [comment]
这网站有搜索功能吗？我找了一圈好像也没看到。。。
如果没有搜索功能的话，就没法做书源，因为《阅读》搜索、换源都需要 "搜索"，除非你只靠 发现 找书，或者手动输入书籍详情页 URL 来加入书架。

**Comment by jy67502** [comment]
> ### 网站地址
> https://sumingxs.com/
> 
> ### 推荐原因
> 《宿命之环》小说在其他所有书源中，都有许多错别字，甚至缺少整句话，这个小说网站，是我看过错别字最少，也没有漏句的。
> 
> 举例： 第一卷 第一百零八章 报告 “我们确定了三件事情”后面，其他书源都漏了一句话，此网站没有漏。
> 
> 第一卷第一百零九章 微小的希望 “留着小胡子的男人顿时有了谈兴”后面，其他书源都漏了一句话，此网站没有漏。

老哥，这个书源挂了，你有他新的地址吗

**Comment by jy67502** [comment]
> ### 网站地址
> https://sumingxs.com/
> 
> ### 推荐原因
> 《宿命之环》小说在其他所有书源中，都有许多错别字，甚至缺少整句话，这个小说网站，是我看过错别字最少，也没有漏句的。
> 
> 举例： 第一卷 第一百零八章 报告 “我们确定了三件事情”后面，其他书源都漏了一句话，此网站没有漏。
> 
> 第一卷第一百零九章 微小的希望 “留着小胡子的男人顿时有了谈兴”后面，其他书源都漏了一句话，此网站没有漏。

@xiaowonet  大哥，这个网站挂了，有新的地址吗
