### ISSUE TITLE
书源请求：gutenberg, archive, openlibrary

### ISSUE THREAD

**Issue by Pantyhose-X** [XIU2/Yuedu#95]
### 网站地址

https://gutenberg.org
https://archive.org/details/texts
https://openlibrary.org

### 推荐原因

源仓库 找不到英文书源。

> gutenberg [刘易斯·卡罗尔的《爱丽丝梦游仙境》](https://gutenberg.org/ebooks/11) , [威廉·莎士比亚的《威廉·莎士比亚全集》](https://gutenberg.org/ebooks/100) , [L. Frank Baum 的《绿野仙踪》](https://gutenberg.org/ebooks/55),  [简·奥斯汀的《傲慢与偏见》](https://gutenberg.org/ebooks/1342), [柏拉图的《理想国》](https://gutenberg.org/ebooks/1497)  等
> archive：JRR托尔金的 《霍比特人》和《指环王》等.

这几个是优秀的英文 公共 书源！

Legado 可能需要绕过cloudflare https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/network/CloudflareKiller.kt

国内无法直连访问： host_resolver_rules 规避 DNS 污染，以及使用 QUIC 实现直连 
例子 https://github.com/UjuiUjuMandan/EhViewer

**Comment by XIU2** [comment]
我写了那么多 申请必读 你看都不看？
